repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.7
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix, --config=pyproject.toml ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]
      args: [ --config=pyproject.toml ]
